config/routes.rb
Rails.application.routes.draw do

  root "sessions#new"
  resources :sessions, only: [:new, :destroy]

  resources :events, only: [:index, :show]
  get '/create_events', to: "events#create_events", as: :create_events 

  get '/sign-in', to: "sessions#new", as: "sign-in"
  get '/auth/facebook/callback', to: "users#facebook_create"
  get '/auth/google_oauth2/callback', to: "users#google_create"
  get '/new', to: "users#new"
  patch '/new', to: "users#create"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/auth/failure', to: "sessions#failure"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :facebook_user
	before_create :create_uuid 

	private 

	def create_uuid 
		begin
			self.uuid = SecureRandom.uuid 
		end while self.class.exists?(:uuid => uuid)
	end 
	
end

app/models/facebook_user.rb
class FacebookUser < ApplicationRecord
  has_one :google_user, dependent: :destroy 
  has_many :events, dependent: :destroy 
  before_create :create_uuid

  private 

  def create_uuid 
    begin
      self.uuid = SecureRandom.uuid 
    end while self.class.exists?(:uuid => uuid)
  end

  protected

  def self.create_user(auth_hash)
    self.create(
      username: auth_hash.info.name,
      picture: auth_hash.info.image,
      token: auth_hash.credentials.token
    )
  end 

end

app/models/google_user.rb
class GoogleUser < ApplicationRecord
  belongs_to :facebook_user 
  before_create :create_uuid

  private 

  def create_uuid 
    begin
      self.uuid = SecureRandom.uuid 
    end while self.class.exists?(:uuid => uuid)
  end 

  protected

  def self.create_user(auth_hash, fb_user_id)
    self.create(
      username: auth_hash.info.name,
      email: auth_hash.info.email,
      picture: auth_hash.info.image,
      token: auth_hash.credentials.token,
      refresh_token: auth_hash.credentials.refresh_token,
      facebook_user_id: fb_user_id
    )
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= (FacebookUser.find_by(uuid: session[:user_uuid]) if session[:user_uuid])
  end


  def fb_client
    Koala::Facebook::API.new(current_user.token)
  end 

  def user_signed_in?
    redirect_to new_session_path if !current_user
  end 
 
  def gmail_user
    Gmail.connect(:xoauth2, current_user.google_user.email, current_user.google_user.token)
  end 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :user_signed_in?
	before_action :check_if_user_has_email_setup

	def index 
		@events = current_user.events
	end 

	def show 
		@event = current_user.events.find_by(uuid: params[:id])
	end 

	def create_events 
		fb_client.get_object("me/events/not_replied").each do |event|
			if !current_user.events.find_by(fb_event_id: event["id"]) && event["start_time"] > Time.now
				current_user.events.create(
					name: event["name"],
					info: event["description"],
					date: event["start_time"].to_date,
					location: event["place"]["name"] + " " + event["place"]["location"]["street"] + " " + event["place"]["location"]["zip"],
					fb_event_id: event["id"],
					ticket_link: event["ticket_uri"]
				)
			end 
		end 
		send_event_mails
		redirect_to root_path, notice: "Event emails sent." 
	end 

	private 

	def check_if_user_has_email_setup
		redirect_to new_path if current_user.google_user.email.nil?
	end 

	def send_event_mails
		@current_user = current_user
		@google_user_email = current_user.google_user.email
		@current_user.events.where(mailed?: false).each do |event|
			email_address = @google_user_email
			email = gmail_user.compose do 
				to email_address
				subject "New FB Event: " + event.name 
				body "You have a new Facebook event: \n Event Name: " + event.name + ",\n Event Date: " + event.date + ",\n Event Location: " + event.location + ",\n Event Info: " + event.info 
			end 
			begin 
				email.deliver!
				event.update(mailed?: true)
			rescue
				5.times do puts "Email delivery failed! gmail_user may have disconnected." end 
			end 
		end 
	end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def failure
    redirect_to root_path, notice: "Sorry, but you didn't allow access to our app!"
  end

  def destroy
  	gmail_user.logout
    session[:user_uuid] = nil
    redirect_to root_path, :alert => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:new, :create]

  def facebook_create
    if params[:denied]
      redirect_to sessions_path
    else
      if !FacebookUser.find_by(username: auth_hash.info.name)
       @user = FacebookUser.create_user(auth_hash)
      else
        @user = FacebookUser.find_by(username: auth_hash.info.name)
      end
      session[:user_uuid] = @user.uuid
      redirect_to root_path, notice: "Welcome " + @user.username + "! Sign in with Google now."
    end
  end

  def google_create
    if params[:denied]
      redirect_to sessions_path
    else
      if !GoogleUser.find_by(email: auth_hash.info.email)
        GoogleUser.create_user(auth_hash, current_user.id)
      else
        GoogleUser.find_by(email: auth_hash.info.email)
      end
      redirect_to root_path, notice: "Welcome " + current_user.username + "!"
    end
  end


  def create 
    current_user.update(email: params[:facebook_user][:email])
    redirect_to create_events_path, notice: "Email has been updated."
  end 

  private 

  def set_user 
    @user = current_user
  end 

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/mutedphrases_helper.rb
module MutedphrasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% if @events.nil? %>
<h1> No events at this time.</h1>
<% else %>
<section class="ui middle aligned center aligned grid">
  <ul>
    <% @events.each do |event| %>
     <li> <%= link_to event.name, event_path(event.uuid)%> </li>
     <li> <%= event.info %> </li>
     <li> <%= event.date %> </li>
     <li> <%= event.location %> </li><br><br>
    <% end %>
  </ul>
</section>
<% end %>

app/views/events/show.html.erb
<section class="ui middle aligned center aligned grid">
  <ul>
     <li> <%= @event.name %> </li>
     <li> <%= @event.info %> </li>
     <li> <%= @event.date %> </li>
     <li> <%= @event.location %> </li>
  </ul>
</section>

app/views/layouts/_flash.html.erb
<% if flash[:alert] || flash[:notice] %>
 <div class="ui error message middle aligned center aligned grid">
 <i class="close icon"></i>
 <div class="column">
    <p>
      <%= flash[:alert]%>
    </p>
    <p>
      <%= flash[:notice]%>
    </p>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<section class="ui secondary menu">
  <% if current_user %>
  <section class="right menu">
    <i class="header item">Welcome, <%=current_user.username %></i>
    <%= link_to("Logout", logout_path, class: "item") %>
    <% end %>
  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FB Timeout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2/semantic.min.css' %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2/semantic.min.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js" %>

  </head>

  <body>
  <%= render "layouts/flash" %>
    <section>
      <section class="ui middle aligned center aligned grid">
        <div class="column">
          <h1>FB Timeout</h1>
          <p>
            Stay off Facebook, but stay connected with email notifications of event invites.
          </p>
        </div>
      </section>
    </section>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for(@user, url: new_path) do |f| %>
<%= f.text_field :email, placeholder: "What email should events be sent to?" %>
<%= f.submit "Submit" %>
<% end %>